name: windows-sqlite-test

on:
  push:
    branches: [test-windows-sqlite]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm i -g purescript@0.15.15

      - name: Test spago init
        run: |
          mkdir test-init
          cd test-init
          node --no-warnings=ExperimentalWarning ../bin/bundle.js init --package-set 29.3.0
